using System;
using Licenta.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Licenta.Services
{
    public interface IPdfService
    {
        byte[] GeneratePrescription(MedicalRecord record);
    }

    public class PdfService : IPdfService
    {
        public byte[] GeneratePrescription(MedicalRecord record)
        {
            if (record == null)
                throw new ArgumentNullException(nameof(record));

            var patientName = record.Patient?.User?.FullName
                                 ?? record.Patient?.User?.Email
                                 ?? "Unspecified";

            var doctorName = record.Doctor?.User?.FullName
                                 ?? record.Doctor?.User?.Email
                                 ?? "Unspecified";

            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(30);
                    page.DefaultTextStyle(x => x.FontSize(11));

                    page.Content().Column(col =>
                    {
                        col.Item().Text("PRESCRIPTION AND MEDICAL RECOMMENDATIONS")
                            .Bold()
                            .FontSize(18)
                            .Underline()
                            .AlignCenter();

                        col.Item().Text($"Patient: {patientName}");
                        col.Item().Text($"Doctor: {doctorName}");
                        col.Item().Text($"Visit Date: {record.VisitDateUtc.ToLocalTime():f}");
                        col.Item().LineHorizontal(1);

                        col.Item().PaddingTop(10).Text("Diagnosis").Bold();
                        col.Item().Text(string.IsNullOrWhiteSpace(record.Diagnosis)
                            ? "-"
                            : record.Diagnosis);

                        col.Item().PaddingTop(10).Text("Symptoms and Notes").Bold();
                        col.Item().Text(string.IsNullOrWhiteSpace(record.Notes)
                            ? "-"
                            : record.Notes);

                        col.Item().PaddingTop(10).Text("Treatment / Recommendations").Bold();
                        col.Item().Text(string.IsNullOrWhiteSpace(record.Treatment)
                            ? "-"
                            : record.Treatment);
                    });

                    page.Footer()
                        .AlignRight()
                        .Text($"Automatically generated by system - {DateTime.Now:f}")
                        .FontSize(9)
                        .Italic();
                });
            });

            return document.GeneratePdf();
        }
    }
}